config/routes.rb
OlgasHelpers::Application.routes.draw do

  resources :clients

  root :to => "home#index"

  get '/index', to: 'home#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :caretakers
  resources :managements
  resources :clients

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/caretaker.rb
class Caretaker < ActiveRecord::Base

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/caretakers_controller.rb
class CaretakersController < ApplicationController

  before_action :set_caretaker, only: [:show, :edit, :update, :destroy]

  # GET /caretakers
  # GET /caretakers.json
  def index
    @caretakers = Caretaker.all
  end

  # GET /caretakers/1
  # GET /caretakers/1.json
  def show
  end

  # GET /caretakers/new
  def new
    @caretaker = Caretaker.new
  end

  # GET /caretakers/1/edit
  def edit
  end

  # POST /caretakers
  # POST /caretakers.json
  def create
    @caretaker = Caretaker.new(caretaker_params)

    respond_to do |format|
      if @caretaker.save
        format.html { redirect_to :back, notice: 'Caretaker was successfully created.' }
        format.json { render action: 'show', status: :created, location: @caretaker }
      else
        format.html { render action: 'new' }
        format.json { render json: @caretaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caretakers/1
  # PATCH/PUT /caretakers/1.json
  def update
    respond_to do |format|
      if @caretaker.update(caretaker_params)
        format.html { redirect_to :back, notice: 'Caretaker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @caretaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caretakers/1
  # DELETE /caretakers/1.json
  def destroy
    @caretaker.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_caretaker
    @caretaker = Caretaker.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def caretaker_params
    params.require(:caretaker).permit(:first_name, :last_name, :email, :age, :nationality, :comment, :citizen, :car, :driver_license, :english)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to :back, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to :back, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def client_params
    params.require(:client).permit(:first_name, :last_name, :email, :home_number, :mobile_phone, :fax_number, :street, :state, :zip, :nationality, :languages, :english, :years, :hha, :driver_license, :car, :notes)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @url_link = root_path;
  end
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController

  # GET /caretakers
  def index
    @user = User.all
    @caretaker = Caretaker.new
    @client = Client.new
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/caretakers_helper.rb
module CaretakersHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/views/caretakers/_form.html.erb
<%= f.label :first_name %>
<%= f.text_field :first_name, :autofocused => true, :class => 'form-control', :id => 'expand-form' %>

<%= f.label :last_name %>
<%= f.text_field :last_name, :class => 'form-control', :id => 'expand-form' %>

<%= f.label :email %>
<%= f.text_field :email, :class => 'form-control', :id => 'expand-form', :required => false %>

<%= f.label :age %>
<%= f.text_field :age, :class => 'form-control', :id => 'expand-form', :required => false %>

<%= f.label :nationality %>
<%= f.text_field :nationality, :class => 'form-control', :id => 'expand-form', :required => false %>

<%= f.label :comment %>
<%= f.text_area :comment, :class => 'form-control', :id => 'expand-form', :required => false %>

<br/>
<%= f.label "Citizen?" %>
<%= f.check_box :citizen, {}, true, false %> <br/>

<%= f.label "Has A Car?" %>
<%= f.check_box :car, {}, true, false %> <br/>

<%= f.label "Has Driver License?" %>
<%= f.check_box :driver_license, {}, true, false %> <br/>

<%= f.label "English (1 = bad, 9 = fluent)" %>
<%= f.select :english, 1..9 %> <br/>

app/views/caretakers/_newct.html.erb
<div class='management-window'>


  <%= simple_form_for @caretaker, :class => 'form-expandable', :url => {:controller => "caretakers", :action => "create"} do |f| %>
      <%= f.error_notification %>
      <h3 class="expanderHead"><span class="expanderSign" style="cursor:pointer;">[+]</span> Add Caretaker</h3>

      <div class='expanderContent'>
        <div class="form-inputs">

          <%= render :partial => 'caretakers/form', :locals => {f: f} %>



          <div class="form-actions">
            <%= f.button :submit, 'Create', :class => 'btn-primary' %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/caretakers/_updatect.html.erb
<div class='management-window'>

  <h3 class="expanderHead"><span class="expanderSign" style="cursor:pointer;">[+]</span> Update Caretaker</h3>

  <div class='expanderContent'>
    <div class="form-inputs">
      <% Caretaker.all.map.each do |caretaker| %>
          <h4 class="expanderHead" id="updateExpanderHead"><span class="expanderSign" style="cursor:pointer;">[+]</span><span style="max-width=250px,class=" name-button"><%= " " + caretaker.first_name + caretaker.last_name %></span><span style="float:right"><%= link_to "DELETE", {:controller => :caretakers,
                                                                                                                                                                                                                                                                                         :action => 'destroy', :id => caretaker.id}, data: {confirm: 'Are you sure?'}, :method => :delete %></span>
          </h4>

          <div class='expanderContent'>
            <div class="inner-content">
              <%= simple_form_for @caretaker, :class => 'form-expandable', :url => {:controller => :caretakers,
                                                                                    :action => 'update', :id => caretaker.id}, :method => :patch do |f| %>

                  <%= f.label :first_name %>
                  <%= f.text_field :first_name, :autofocused => true, :value => caretaker.first_name, :class => 'form-control', :id => 'expand-form' %>

                  <%= f.label :last_name %>
                  <%= f.text_field :last_name, :value => caretaker.last_name, :class => 'form-control', :id => 'expand-form' %>

                  <%= f.label :email %>
                  <%= f.text_field :email, :value => caretaker.email, :class => 'form-control', :id => 'expand-form', :required => false %>

                  <%= f.label :age %>
                  <%= f.text_field :age, :class => 'form-control', :value => caretaker.age, :id => 'expand-form', :required => false %>

                  <%= f.label :nationality %>
                  <%= f.text_field :nationality, :value => caretaker.nationality, :class => 'form-control', :id => 'expand-form', :required => false %>

                  <%= f.label :comment %>
                  <%= f.text_area :comment, :value => caretaker.comment, :class => 'form-control', :id => 'expand-form', :required => false %>

                  <br/>
                  <% if caretaker.car == true %>
                      <%= f.label "Citizen?" %>
                      <%= f.check_box :citizen, {:value => caretaker.citizen, :checked => true}, checked_value: true, unchacked_value: false %>
                      <br/>
                  <% else %>
                      <%= f.check_box :citizen, {:value => caretaker.citizen}, checked_value: true, unchacked_value: false %>
                      <br/>
                  <% end %>

                  <%= f.label "Has A Car?" %>
                  <% if caretaker.car == true %>
                      <%= f.check_box :car, {:value => caretaker.car, :checked => true}, checked_value: true, unchacked_value: false %>
                      <br/>
                  <% else %>
                      <%= f.check_box :car, {:value => caretaker.car}, checked_value: true, unchacked_value: false %>
                      <br/>
                  <% end %>

                  <%= f.label "Has Driver License?" %>
                  <% if caretaker.driver_license == true %>
                      <%= f.check_box :driver_license, {:value => caretaker.driver_license, :checked => true}, checked_value: true, unchacked_value: false %>
                      <br/>
                  <% else %>
                      <%= f.check_box :driver_license, {:value => caretaker.driver_license}, checked_value: true, unchacked_value: false %>
                      <br/>
                  <% end %>

                  <%= f.label "English (1 = bad, 9 = fluent)" %>
                  <%= f.select :english, 1..9, :selected => caretaker.english.to_i %> <br/>

                  <div class="form-actions">
                    <%= f.button :submit, 'Update', :class => 'btn-primary' %>
                  </div>
              <% end %>
            </div>
          </div>

      <% end %>
    </div>
  </div>
  </h4>
</div>

app/views/caretakers/edit.html.erb
<h1>Editing caretaker</h1>

<%= render 'form' %>

<%= link_to 'Show', @caretaker %> |
<%= link_to 'Back', caretakers_path %>

app/views/caretakers/index.html.erb
<h1>Listing caretakers</h1>

<table>
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Age</th>
    <th>Nationality</th>
    <th>Comment</th>
    <th>Citizen</th>
    <th>Car</th>
    <th>Driver license</th>
    <th>English</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @caretakers.each do |caretaker| %>
      <tr>
        <td><%= caretaker.first_name %></td>
        <td><%= caretaker.last_name %></td>
        <td><%= caretaker.email %></td>
        <td><%= caretaker.age %></td>
        <td><%= caretaker.nationality %></td>
        <td><%= caretaker.comment %></td>
        <td><%= caretaker.citizen %></td>
        <td><%= caretaker.car %></td>
        <td><%= caretaker.driver_license %></td>
        <td><%= caretaker.english %></td>
        <td><%= link_to 'Show', caretaker %></td>
        <td><%= link_to 'Edit', edit_caretaker_path(caretaker) %></td>
        <td><%= link_to 'Destroy', caretaker, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caretaker', new_caretaker_path %>

app/views/caretakers/new.html.erb
<h1>New caretaker</h1>

<%= render 'form' %>

<%= link_to 'Back', caretakers_path %>

app/views/caretakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @caretaker.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @caretaker.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @caretaker.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @caretaker.age %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @caretaker.nationality %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @caretaker.comment %>
</p>

<p>
  <strong>Citizen:</strong>
  <%= @caretaker.citizen %>
</p>

<p>
  <strong>Car:</strong>
  <%= @caretaker.car %>
</p>

<p>
  <strong>Driver license:</strong>
  <%= @caretaker.driver_license %>
</p>

<p>
  <strong>English:</strong>
  <%= @caretaker.english %>
</p>

<%= link_to 'Edit', edit_caretaker_path(@caretaker) %> |
<%= link_to 'Back', caretakers_path %>

app/views/clients/_form.html.erb
<%= f.label :first_name %>
<%= f.text_field :first_name, :autofocused => true, :class => 'form-control', :id => 'expand-form' %>

<%= f.label :last_name %>
<%= f.text_field :last_name, :class => 'form-control', :id => 'expand-form' %>

<%= f.label :email %>
<%= f.text_field :email, :class => 'form-control', :id => 'expand-form' %>

<%= f.label "Home Number" %>
<%= f.text_field :home_number, :class => 'form-control', :id => 'expand-form' %>

<%= f.label "Mobile Phone" %>
<%= f.text_field :mobile_phone, :class => 'form-control', :id => 'expand-form' %>

<%= f.label "Fax Number" %>
<%= f.text_field :fax_number, :class => 'form-control', :id => 'expand-form' %>

<%= f.label "Street Address" %>
<%= f.text_field :street, :class => 'form-control', :id => 'expand-form' %>

<%= f.label "State" %>
<%= f.text_field :state, :class => 'form-control', :id => 'expand-form' %>

<%= f.label "Zip" %>
<%= f.text_field :zip, :class => 'form-control', :id => 'expand-form' %>

<%= f.label :nationaity %>
<%= f.text_field :nationality, :class => 'form-control', :id => 'expand-form' %>

<%= f.label "Languages Spoken" %>
<%= f.text_field :languages, :class => 'form-control', :id => 'expand-form' %>

<%= f.label "Years in US" %>
<%= f.text_field :years, :class => 'form-control', :id => 'expand-form' %>

<%= f.label :notes %>
<%= f.text_area :notes, :class => 'form-control', :id => 'expand-form', :required => false %>

<%= f.label "HHA Number" %>
<%= f.text_field :hha, :class => 'form-control', :id => 'expand-form' %>

<%= f.label "English (1 = bad, 9 = fluent)" %>
<%= f.select :english, 1..9 %> <br/>

<%= f.label "Has A Car?" %>
<%= f.check_box :car, {}, true, false %> <br/>

<%= f.label "Has Driver License?" %>
<%= f.check_box :driver_license, {}, true, false %> <br/>

app/views/clients/_newcl.erb
<div class='management-window'>


  <%= simple_form_for @client, :class => 'form-expandable', :url => {:controller => "clients", :action => "create"} do |f| %>
      <%= f.error_notification %>
      <h3 class="expanderHead"><span class="expanderSign" style="cursor:pointer;">[+]</span> Add Client</h3>

      <div class='expanderContent'>
        <div class="form-inputs">

          <%= render :partial => 'clients/form', :locals => {f: f} %>



          <div class="form-actions">
            <%= f.button :submit, 'Create', :class => 'btn-primary' %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Home number</th>
    <th>Mobile phone</th>
    <th>Fax number</th>
    <th>Street</th>
    <th>State</th>
    <th>Zip</th>
    <th>Nationality</th>
    <th>Languages</th>
    <th>English</th>
    <th>Years</th>
    <th>Hha</th>
    <th>Driver license</th>
    <th>Car</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.email %></td>
        <td><%= client.home_number %></td>
        <td><%= client.mobile_phone %></td>
        <td><%= client.fax_number %></td>
        <td><%= client.street %></td>
        <td><%= client.state %></td>
        <td><%= client.zip %></td>
        <td><%= client.nationality %></td>
        <td><%= client.languages %></td>
        <td><%= client.english %></td>
        <td><%= client.years %></td>
        <td><%= client.hha %></td>
        <td><%= client.driver_license %></td>
        <td><%= client.car %></td>
        <td><%= client.notes %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @client.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Home number:</strong>
  <%= @client.home_number %>
</p>

<p>
  <strong>Mobile phone:</strong>
  <%= @client.mobile_phone %>
</p>

<p>
  <strong>Fax number:</strong>
  <%= @client.fax_number %>
</p>

<p>
  <strong>Street:</strong>
  <%= @client.street %>
</p>

<p>
  <strong>State:</strong>
  <%= @client.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @client.zip %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @client.nationality %>
</p>

<p>
  <strong>Languages:</strong>
  <%= @client.languages %>
</p>

<p>
  <strong>English:</strong>
  <%= @client.english %>
</p>

<p>
  <strong>Years:</strong>
  <%= @client.years %>
</p>

<p>
  <strong>Hha:</strong>
  <%= @client.hha %>
</p>

<p>
  <strong>Driver license:</strong>
  <%= @client.driver_license %>
</p>

<p>
  <strong>Car:</strong>
  <%= @client.car %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @client.notes %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-container">
    <div class="navbar-header">
      <%= link_to "Olga's Helpers", root_url, :class => 'navbar-brand' %>
      <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <i class="icon-reorder"></i>
      </a>
    </div>
    <div id="nav-collapse" class="collapse navbar-collapse navbar-ex1-collapse" style="height: 1px">
      <ul class="nav navbar-nav navbar-right">
        <!--<li class="active"><a title="Home page" class="scroll brand-1" href="#home">Home</a></li>-->
        <% if current_page? (root_path) %>
            <li><%= link_to "Home", '#home', :title => 'Home Page', :class => 'scroll brand-1' %></li>
            <li><a title="Check out our awesome services" href="#features" class=" scroll brand-4">Features</a></li>
            <li><a title="Themes assets" href="#assets" class="scroll brand-3">Assets</a></li>
            <li><a title="Who we are" href="#about" class="scroll fadeto brand-4"> About us</a></li>
            <li><a title="Get in touch!" href="#contact" class="scroll brand-2">Contact</a></li>

        <% else %>
            <li><%= link_to "Home", root_path + '#home', :title => 'Home Page', :class => 'scroll brand-1' %></li>
            <li><%= link_to "Features", root_path + '#features', :title => 'Features', :class => 'scroll brand-4' %></li>
            <li><%= link_to "Assets", root_path + '#fassets', :title => 'Themes assets', :class => 'scroll brand-3' %></li>
            <li><%= link_to "About Us", root_path + '#about', :title => 'Who we are', :class => 'scroll fedato brand-4' %></li>
            <li><%= link_to "Contact", root_path + '#contact', :title => 'Get in touch!', :class => 'scroll brand-2' %></li>
        <% end %>

        <% if user_signed_in? %>
            <li style="height: 47px" class="hoverli">

              <% User.all.map.each do |user| %>
                  <a class="scroll brand-4" data-toggle="dropdown" href="#"><%= "#{user.name.capitalize}" %></a>
              <% end %>

              <ul class="dropdown-menu navbar-inverse file_menu" role="menu">
                <li class="scroll brand-4">
                  <%= link_to 'My Account', edit_user_registration_path, :style => "color:white" %>
                </li>
                <% if current_user.has_role? :admin %>
                    <li class="scroll brand-4">
                      <!--<%= link_to 'Admin', users_path %>-->
                      <%= link_to 'Management', managements_path, :style => "color:white" %>
                    </li>
                <% end %>
                <li class="scroll fedato brand-4">
                  <%= link_to 'Logout', destroy_user_session_path, :method => 'delete', :style => "color:white" %>
                </li>
              </ul>

            </li>

        <% else %>

            <li>
              <%= link_to 'Login', new_user_session_path, :class => 'scroll brand-4' %>
            </li>
            <li>
              <%= link_to 'Sign up', new_user_registration_path, :class => 'scroll brand-4' %>
            </li>
        <% end %>

      </ul>
    </div>
  </div>
  <!-- /.navbar-collapse -->
</nav>

<script>
    $(document).ready(function () {
        $(".hoverli").hover(
                function () {
                    $('ul.file_menu').slideDown('slow');
                },
                function () {
                    $('ul.file_menu').slideUp('medium');
                }
        );

    });
</script>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal'} do |f| %>
      <div class="modal-header">
        <a class="close" data-dismiss="modal">&#215;</a>

        <h3>Change Role</h3>
      </div>
      <div class="modal-body">
        <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda { |t| t.name.titleize }, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
      </div>
      <div class="modal-footer">
        <%= f.submit "Change Role", :class => "btn" %>
        <a class="btn" data-dismiss="modal" href="#">Close</a>
      </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
  <table class="table table-condensed">
    <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at.to_date %></td>
          <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
          <td>
            <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change
              role</a>
            <%= render user %>
          </td>
          <td><%= link_to("Delete user", user_path(user), :data => {:confirm => "Are you sure?"}, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>